spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: worker
          uri: lb://worker
          predicates:
            - Path=/workers/**   
          filters:
            - StripPrefix=0

        - id: payroll
          uri: lb://payroll
          predicates:
            - Path=/payments/**  
          filters:
            - StripPrefix=0

        - id: user
          uri: lb://user
          predicates:
            - Path=/users/** 
          filters:
            - StripPrefix=0

        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
            - RemoveRequestHeader=Cookie

server:
  port: 8765

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
