spring:
  datasource:
    url: jdbc:postgresql://hr-user-pg16:5432/db_hr_user  
    username: postgres
    password: 1234567

  jpa:
    hibernate:
      ddl-auto: create  #cria as tabelas
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
