spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/db_hr_user  #porta 5434
    username: postgres
    password: 1234567

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true  #garante que JPA cria as tabelas antes do data.sql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always  #garante que o data.sql sempre seja executado
